--- #YAML:1.0
name:               Tie-Pick
version:            2009110701
abstract:           Randomly pick (and remove) an element from a set.
author:
    - Abigail <cpan@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:      0
    perl:      5.006
    strict:    0
    warnings:  0
resources:
    repository:  git://github.com/Abigail/tie--pick.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:  []
test_requires:
    strict:    0
    warnings:  0
